name: Create SharePoint List Item

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  create-item:
    runs-on: windows-latest  # Use a Windows runner for PowerShell 5.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PnP PowerShell
      run: |
        Install-Module -Name "PnP.PowerShell" -Force -AllowClobber -Scope CurrentUser

    - name: Run PowerShell script to create SharePoint list item
      env:
        SITE_URL: ${{ secrets.SITE_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        LIST_NAME: ${{ secrets.LIST_NAME }}
        TITLE: "GitHub Action Created Item"
        STATUS: "Started"
      run: |
        pwsh ./PowerShell/CreateListItem.ps1 -siteUrl $env:SITE_URL -clientId $env:CLIENT_ID -clientSecret $env:CLIENT_SECRET -listName $env:LIST_NAME -title $env:TITLE -status $env:STATUS
